#./src/decoder
SRC_DECODER = decoder.cpp decoder_tree.cpp
TEST_DECODER = decoder_tree_tests.cpp

SRC_FILES += $(patsubst %,decoder/%,$(SRC_DECODER))
TEST_FILES += $(patsubst %,decoder/%,$(TEST_DECODER))